name: emote_this
description: "A new Flutter project."
publish_to: 'none'
version: 1.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.1.4
  logger: ^2.0.2+1
  flutter_bloc: ^8.1.5
  gap: ^3.0.1
  get_it: ^7.7.0
  equatable: ^2.0.5
  shared_preferences: ^2.3.1
  cupertino_icons: ^1.0.8
  characters: ^1.2.0
  fl_chart: ^0.69.2
  emoji_picker_flutter: ^3.1.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  haptic_feedback: ^0.5.1+1
  share_plus: ^10.1.3
  core_logic:
    git:
      url: https://github.com/Vennylost/core_logic.git
      ref: 0d02185756dc00d23f636f2f45ed4b889337321c

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/json/
    - assets/generated/
  fonts:
    - family: Baloo Bhaijaan
      fonts:
        - asset: assets/fonts/baloo.ttf
          weight: 400